In [1]:
# ESV DERIVED FROM https://versenotes.org/a-list-of-books-in-the-bible-by-number-of-chapters/ FILES
# RUN 'general.ipynb' & 'esv.py' & 'esv_sections.ipynb' FIRST

import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

esv = pd.read_csv('ESV/ESV Books.csv')
general = pd.read_csv('General/Bible Books (General).csv')

In [2]:
esv.head()

,Book,Chapters,Verses,Words,Vs/Ch,Wd/Ch,Wd/Vs,Time (150 WPM),Time (200 WPM),Time (250 WPM)
0,Genesis,50,1533,36397,30.7,727.9,23.7,4hr 2m,3hr 1m,2hr 25m
1,Exodus,40,1213,31005,30.3,775.1,25.6,3hr 26m,2hr 35m,2hr 4m
2,Leviticus,27,859,23493,31.8,870.1,27.3,2hr 36m,1hr 57m,1hr 33m
3,Numbers,36,1288,31043,35.8,862.3,24.1,3hr 26m,2hr 35m,2hr 4m
4,Deuteronomy,34,959,27618,28.2,812.3,28.8,3hr 4m,2hr 18m,1hr 50m

In [3]:
general.head()

,Book,Chapters,Verses,Words,Vs/Ch,Wd/Ch,Wd/Vs,Time (150 WPM),Time (200 WPM),Time (250 WPM)
0,Genesis,50,1550,35000,31.0,700.0,22.6,3hr 53m,2hr 55m,2hr 20m
1,Exodus,40,1210,32700,30.2,817.5,27.0,3hr 38m,2hr 43m,2hr 10m
2,Leviticus,27,860,24500,31.9,907.4,28.5,2hr 43m,2hr 2m,1hr 38m
3,Numbers,36,1290,32900,35.8,913.9,25.5,3hr 39m,2hr 44m,2hr 11m
4,Deuteronomy,34,960,28000,28.2,823.5,29.2,3hr 6m,2hr 20m,1hr 52m

In [4]:
df = pd.DataFrame()
df['Book'] = esv['Book']
df['Chapters'] = esv['Chapters'] - general['Chapters']
df['Verses'] = esv['Verses'] - general['Verses']
df['Words'] = esv['Words'] - general['Words']
df

               Book  Chapters  Verses  Words
0           Genesis         0     -17   1397
1            Exodus         0       3  -1695
2         Leviticus         0      -1  -1007
3           Numbers         0      -2  -1857
4       Deuteronomy         0      -1   -382
5            Joshua         0      -2   -607
6            Judges         0      -2   -188
7              Ruth         0       0   -133
8          1 Samuel         0       0  -1332
9          2 Samuel         0       0  -4205
10          1 Kings         0       1  -1480
11          2 Kings         0      -1   -588
12     1 Chronicles         0       2  -1770
13     2 Chronicles         0       2  -1244
14             Ezra         0       0   -529
15         Nehemiah         0       1  -2126
16           Esther         0      -3   -116
17              Job         0       0   -473
18           Psalms         0       1  -1727
19         Proverbs         0       0   -498
20     Ecclesiastes         0       2   -204
21  Song of Solomon         0      -3    -74
22           Isaiah         0       2  -2015
23         Jeremiah         0      -1  -2106
24     Lamentations         0      -1    243
25          Ezekiel         0      -2  -2091
26           Daniel         0      -3   -328
27            Hosea         0      -3   -194
28             Joel         0      -2   -113
29             Amos         0       1   -183
30          Obadiah         0       0    -56
31            Jonah         0      -2     -8
32            Micah         0       0   -128
33            Nahum         0      -3   -189
34         Habakkuk         0       1   -107
35        Zephaniah         0       3    -47
36           Haggai         0      -2    -35
37        Zechariah         0       1   -367
38          Malachi         0       0    -28
39          Matthew         0      -3   -331
40             Mark         0      -7   -354
41             Luke         0      -1     10
42             John         0     -14   3191
43             Acts         0      -7   -867
44           Romans         0       2     30
45    1 Corinthians         0      -3   -686
46    2 Corinthians         0      -3     77
47        Galatians         0    -101     33
48        Ephesians         0       0     -6
49      Philippians         0      -1    -20
50       Colossians         0       0    -30
51  1 Thessalonians         0      -1     14
52  2 Thessalonians         0      -3     45
53        1 Timothy         0       3     64
54        2 Timothy         0       1     47
55            Titus         0       1     28
56         Philemon         0       0     31
57          Hebrews         0       3    -65
58            James         0      -2     31
59          1 Peter         0       0    -75
60          2 Peter         0       1     -1
61           1 John         0       0    207
62           2 John         0       0      2
63           3 John         0       1     13
64             Jude         0       0      0
65       Revelation         0       4   -424

In [5]:
esv_sections = pd.read_csv('ESV/ESV Sections.csv')
general_sections = pd.read_csv('General/Bible Sections (General).csv')

df = pd.DataFrame()
df['Section'] = esv_sections['Section']
df['Books'] = esv_sections['Books'] - general_sections['Books']
df['Chapters'] = esv_sections['Chapters'] - general_sections['Chapters']
df['Verses'] = esv_sections['Verses'] - general_sections['Verses']
df['Words'] = esv_sections['Words'] - general_sections['Words']
df

                    Section  Books  Chapters  Verses  Words
0                     Bible      0         0    -126 -20516
1             Old Testament      0         0      -5 -17530
2             New Testament      0         0     -71  -3986
3                Pentateuch      0         0       2  -3444
4                   History      0         0      18 -15148
5                    Poetry      0         0       0  -2996
6            Major Prophets      0         0       0  -6337
7            Minor Prophets      0         0       0  -2505
8                   Gospels      0         0     -15   1466
9            History (Acts)      0         0      -7   -867
10         Pauline Epistles      0         0    -108   -253
11         General Epistles      0         0       5     42
12  Apocalypse (Revelation)      0         0       4   -424