In [1]:
from bible_stats import BibleStats # My Custom Class for the WPM Function & Constants
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

books_df = pd.read_csv('General/Raw Bible Books (General).csv').set_index('Book') # Dependent on File "General/Raw Bible Books (General).csv"
sections_df = pd.read_csv('General/Raw Bible Sections (General).csv').set_index('Section') # Dependent on File "General/Raw Bible Sections (General).csv"

In [2]:
books_df['Vs/Ch'] = round(books_df['Verses'] / books_df['Chapters'], 1)
books_df['Wd/Ch'] = round(books_df['Words'] / books_df['Chapters'], 1)
books_df['Wd/Vs'] = round(books_df['Words'] / books_df['Verses'], 1)

for time in range(BibleStats.MIN_WPM, BibleStats.MAX_WPM, BibleStats.INCREMENT):
    books_df[f'Time ({time} WPM)'] = books_df['Words'].apply(lambda x: BibleStats.wpm(x, time))
books_df.to_csv('General/Bible Books (General).csv')
books_df

,Chapters,Verses,Words,Vs/Ch,Wd/Ch,Wd/Vs,Time (150 WPM),Time (200 WPM),Time (250 WPM)
Book,,,,,,,,,
Genesis,50,1550,35000,31.0,700.0,22.6,3hr 53m,2hr 55m,2hr 20m
Exodus,40,1210,32700,30.2,817.5,27.0,3hr 38m,2hr 43m,2hr 10m
Leviticus,27,860,24500,31.9,907.4,28.5,2hr 43m,2hr 2m,1hr 38m
Numbers,36,1290,32900,35.8,913.9,25.5,3hr 39m,2hr 44m,2hr 11m
Deuteronomy,34,960,28000,28.2,823.5,29.2,3hr 6m,2hr 20m,1hr 52m
Joshua,24,660,18600,27.5,775.0,28.2,2hr 4m,1hr 33m,1hr 14m
Judges,21,620,18500,29.5,881.0,29.8,2hr 3m,1hr 32m,1hr 14m
Ruth,4,85,2570,21.2,642.5,30.2,17m 8s,12m 51s,10m 16s
1 Samuel,31,810,25500,26.1,822.6,31.5,2hr 50m,2hr 7m,1hr 42m
2 Samuel,24,695,24000,29.0,1000.0,34.5,2hr 40m,2hr 0m,1hr 36m
1 Kings,22,815,25000,37.0,1136.4,30.7,2hr 46m,2hr 5m,1hr 40m
2 Kings,25,720,23500,28.8,940.0,32.6,2hr 36m,1hr 57m,1hr 34m
1 Chronicles,29,940,20350,32.4,701.7,21.6,2hr 15m,1hr 41m,1hr 21m
2 Chronicles,36,820,26100,22.8,725.0,31.8,2hr 54m,2hr 10m,1hr 44m
Ezra,10,280,7450,28.0,745.0,26.6,49m 40s,37m 15s,29m 48s
Nehemiah,13,405,12000,31.2,923.1,29.6,1hr 20m,1hr 0m,48m 0s
Esther,10,170,5600,17.0,560.0,32.9,37m 20s,28m 0s,22m 24s
Job,42,1070,18100,25.5,431.0,16.9,2hr 0m,1hr 30m,1hr 12m
Psalms,150,2460,43000,16.4,286.7,17.5,4hr 46m,3hr 35m,2hr 52m
Proverbs,31,915,15050,29.5,485.5,16.4,1hr 40m,1hr 15m,1hr 0m
Ecclesiastes,12,220,5580,18.3,465.0,25.4,37m 12s,27m 54s,22m 19s
Songs of Solomon,8,120,2650,15.0,331.2,22.1,17m 40s,13m 15s,10m 36s
Isaiah,66,1290,37400,19.5,566.7,29.0,4hr 9m,3hr 7m,2hr 29m
Jeremiah,52,1365,42650,26.2,820.2,31.2,4hr 44m,3hr 33m,2hr 50m
Lamentations,5,155,3010,31.0,602.0,19.4,20m 4s,15m 3s,12m 2s
Ezekiel,48,1275,39400,26.6,820.8,30.9,4hr 22m,3hr 17m,2hr 37m
Daniel,12,360,11600,30.0,966.7,32.2,1hr 17m,58m 0s,46m 24s
Hosea,14,200,5170,14.3,369.3,25.8,34m 28s,25m 51s,20m 40s
Joel,3,75,2030,25.0,676.7,27.1,13m 32s,10m 9s,8m 7s
Amos,9,145,4250,16.1,472.2,29.3,28m 20s,21m 15s,17m 0s
Obadiah,1,21,670,21.0,670.0,31.9,4m 28s,3m 21s,2m 40s
Jonah,4,50,1320,12.5,330.0,26.4,8m 48s,6m 36s,5m 16s
Micah,7,105,3150,15.0,450.0,30.0,21m 0s,15m 45s,12m 36s
Nahum,3,50,1300,16.7,433.3,26.0,8m 40s,6m 30s,5m 12s
Habakkuk,3,55,1480,18.3,493.3,26.9,9m 52s,7m 24s,5m 55s
Zephaniah,3,50,1620,16.7,540.0,32.4,10m 48s,8m 6s,6m 28s
Haggai,2,40,1130,20.0,565.0,28.2,7m 32s,5m 39s,4m 31s
Zechariah,14,210,6450,15.0,460.7,30.7,43m 0s,32m 15s,25m 48s
Malachi,4,55,1780,13.8,445.0,32.4,11m 52s,8m 54s,7m 7s
Matthew,28,1070,23350,38.2,833.9,21.8,2hr 35m,1hr 56m,1hr 33m
Mark,16,680,14950,42.5,934.4,22.0,1hr 39m,1hr 14m,59m 48s
Luke,24,1150,25000,47.9,1041.7,21.7,2hr 46m,2hr 5m,1hr 40m
John,21,880,15650,41.9,745.2,17.8,1hr 44m,1hr 18m,1hr 2m
Acts,28,1010,24500,36.1,875.0,24.3,2hr 43m,2hr 2m,1hr 38m
Romans,16,430,9500,26.9,593.8,22.1,1hr 3m,47m 30s,38m 0s
1 Corinthians,16,440,10000,27.5,625.0,22.7,1hr 6m,50m 0s,40m 0s
2 Corinthians,13,260,6000,20.0,461.5,23.1,40m 0s,30m 0s,24m 0s
Galatians,6,250,3100,41.7,516.7,12.4,20m 40s,15m 30s,12m 24s
Ephesians,6,155,3020,25.8,503.3,19.5,20m 8s,15m 6s,12m 4s
Philippians,4,105,2180,26.2,545.0,20.8,14m 32s,10m 54s,8m 43s
Colossians,4,95,1980,23.8,495.0,20.8,13m 12s,9m 54s,7m 55s
1 Thessalonians,5,90,1840,18.0,368.0,20.4,12m 16s,9m 12s,7m 21s
2 Thessalonians,3,50,1020,16.7,340.0,20.4,6m 48s,5m 6s,4m 4s
1 Timothy,6,110,2250,18.3,375.0,20.5,15m 0s,11m 15s,9m 0s
2 Timothy,4,82,1600,20.5,400.0,19.5,10m 40s,8m 0s,6m 24s
Titus,3,45,900,15.0,300.0,20.0,6m 0s,4m 30s,3m 36s
Philemon,1,25,430,25.0,430.0,17.2,2m 52s,2m 9s,1m 43s
Hebrews,13,300,7000,23.1,538.5,23.3,46m 40s,35m 0s,28m 0s
James,5,110,2300,22.0,460.0,20.9,15m 20s,11m 30s,9m 12s
1 Peter,5,105,2480,21.0,496.0,23.6,16m 32s,12m 24s,9m 55s
2 Peter,3,60,1550,20.0,516.7,25.8,10m 20s,7m 45s,6m 12s
1 John,5,105,2300,21.0,460.0,21.9,15m 20s,11m 30s,9m 12s
2 John,1,13,300,13.0,300.0,23.1,2m 0s,1m 30s,1m 12s
3 John,1,14,290,14.0,290.0,20.7,1m 56s,1m 27s,1m 9s
Jude,1,25,610,25.0,610.0,24.4,4m 4s,3m 3s,2m 26s
Revelation,22,400,11950,18.2,543.2,29.9,1hr 19m,59m 45s,47m 48s

In [3]:
sections_df['Ch/Book'] = round(sections_df['Chapters'] / sections_df['Books'], 1)
sections_df['Vs/Book'] = round(sections_df['Verses'] / sections_df['Books'], 1)
sections_df['Wd/Book'] = round(sections_df['Words'] / sections_df['Books']).astype('int')

sections_df['Vs/Ch'] = round(sections_df['Verses'] / sections_df['Chapters'], 1)
sections_df['Wd/Ch'] = round(sections_df['Words'] / sections_df['Chapters'], 1)
sections_df['Wd/Vs'] = round(sections_df['Words'] / sections_df['Verses'], 1)

for time in range(BibleStats.MIN_WPM, BibleStats.MAX_WPM, BibleStats.INCREMENT):
    sections_df[f'Time ({time} WPM)'] = sections_df['Words'].apply(lambda x: BibleStats.wpm(x, time))
sections_df.to_csv('General/Bible Sections (General).csv')
sections_df

,Books,Chapters,Verses,Words,Ch/Book,Vs/Book,Wd/Book,Vs/Ch,Wd/Ch,Wd/Vs,Time (150 WPM),Time (200 WPM),Time (250 WPM)
Section,,,,,,,,,,,,,
Bible,66,1189,31200,780000,18.0,472.7,11818,26.2,656.0,25.0,86hr 40m,65hr 0m,52hr 0m
Old Testament,39,929,23150,600000,23.8,593.6,15385,24.9,645.9,25.9,66hr 40m,50hr 0m,40hr 0m
New Testament,27,260,8000,181000,9.6,296.3,6704,30.8,696.2,22.6,20hr 6m,15hr 5m,12hr 4m
Pentateuch,5,187,5850,153000,37.4,1170.0,30600,31.3,818.2,26.2,17hr 0m,12hr 45m,10hr 12m
History,12,249,7000,210000,20.8,583.3,17500,28.1,843.4,30.0,23hr 20m,17hr 30m,14hr 0m
Poetry,5,243,4785,84400,48.6,957.0,16880,19.7,347.3,17.6,9hr 22m,7hr 2m,5hr 37m
Major Prophets,5,183,4440,134100,36.6,888.0,26820,24.3,732.8,30.2,14hr 54m,11hr 10m,8hr 56m
Minor Prophets,12,67,1050,31400,5.6,87.5,2617,15.7,468.7,29.9,3hr 29m,2hr 37m,2hr 5m
Gospels,4,89,3770,80000,22.2,942.5,20000,42.4,898.9,21.2,8hr 53m,6hr 40m,5hr 20m
History (Acts),1,28,1010,24500,28.0,1010.0,24500,36.1,875.0,24.3,2hr 43m,2hr 2m,1hr 38m
Pauline Epistles,13,87,2140,43700,6.7,164.6,3362,24.6,502.3,20.4,4hr 51m,3hr 38m,2hr 54m
General Epistles,8,34,730,16900,4.2,91.2,2112,21.5,497.1,23.2,1hr 52m,1hr 24m,1hr 7m
Apocalypse (Revelation),1,22,400,11950,22.0,400.0,11950,18.2,543.2,29.9,1hr 19m,59m 45s,47m 48s